In [1]:
import numpy as np
demo = [10,20,30]
np.array(demo)

array([10, 20, 30])

In [2]:
demo2=[10,20,"30"]
np.array(demo2)

array(['10', '20', '30'], dtype='<U11')

In [3]:
demo3=[10,20,"xyz"]
np.array(demo3)

array(['10', '20', 'xyz'], dtype='<U11')

In [7]:
np.zeros(5,int)
xl =np.ones(5)
print(xl)

[1. 1. 1. 1. 1.]


In [30]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [47]:
y=np.zeros(100000000,int)
y.dtype

dtype('int32')

In [54]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [62]:
x5= np.ones(5)

x5[3]=2
print(x5)


[1. 1. 1. 2. 1.]


In [84]:
new_arrays = np.zeros((3,4,5))
print(new_arrays)


new_arrays[0][1][2]
new_arrays[0][1]


[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


array([0., 0., 0., 0., 0.])

In [87]:
new_arrays.shape


a= np.zeros(5)
print(a)
a[2:5]

[0. 0. 0. 0. 0.]


array([0., 0., 0.])

In [88]:
import numpy as np
import math as m




x= [1,2,3]
y= [4,5,6]
zx=x+10

TypeError: can only concatenate list (not "int") to list

In [92]:
x=np.array([1,2,3])
y=np.array([3,5,6])
x=x+11
print(x)
print(x+y)

[12 13 14]
[15 18 20]


In [98]:
p1=np.array([2,2,2])
p2=np.array([1,1,1])

value = ((p1-p2)**2).sum()
print(value)


# val2=value.sum()
# print(val2)

m.sqrt(value)

3


1.7320508075688772

In [3]:
import numpy as np
# import math as m


pts= np.array([4,5,6,7])

value1=((pts-pts.mean())**2).sum()
print(value1)
m.sqrt(value1)

5.0


2.23606797749979

In [ ]:
import pandas as pd
iris_df = pd.read_csv("")